Repository pulp/pulp-oci-images, pull requests merged in 2024-10, with the labels that each got.

#671 Fix base-image CI exiting early when update is needed
  .github/actions/base_images/action.yml
  .github/actions/test_image/action.yml
Labels: multi-commit, no-issue, no-changelog

#674 Fix release failing when there were duplicate tags
  .github/workflows/release.yml
Labels: no-issue, no-changelog

#589 Drop createrepo_c build deps
  images/Containerfile.core.base
Labels: no-issue, no-changelog

#675 Remove old docs publishing workflow
  .ci/scripts/publish_docs.sh
  .github/workflows/docs.yml
Labels: no-issue, no-changelog

#678 Update setup-python action to v5
  .github/actions/build_image/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: no-issue, no-changelog

#680 Fix mislabeled tag in pulp-web publish & simplify compose testing to only pulp-minimal images
  .github/actions/publish_images/action.yml
  .github/actions/test_image/action.yml
Labels: backport-3.49, no-issue, no-changelog

#679 Remove nightly scenario and galaxy images
  .github/actions/build_image/action.yml
  .github/actions/test_image/action.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  images/galaxy-minimal/nightly/Containerfile.core
  images/galaxy-minimal/nightly/Containerfile.webserver
  images/galaxy-minimal/stable/Containerfile.core
  images/galaxy-minimal/stable/Containerfile.webserver
  images/galaxy/nightly/Containerfile
  images/galaxy/settings.py
  images/galaxy/stable/Containerfile
  images/s6_assets/galaxy_ng_tests.sh
  images/s6_assets/test.sh
Labels: multi-commit, no-issue, no-changelog

#685 Update actions to latest version and set CI python to 3.11 [3.49]
  .github/actions/build_image/action.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/kanban.yml
  .github/workflows/release.yml
Labels: multi-commit, no-issue, no-changelog

#689 Fix cache invalidation command
  .github/actions/base_images/action.yml
  .github/workflows/ci.yml
Labels: no-issue, no-changelog

#688 Have cache invalidation not run on pull requests
  .github/actions/base_images/action.yml
  .github/workflows/ci.yml
Labels: no-issue, no-changelog

#690 Remove Opentelemetry instrumentation agent from the runtime
  docs/admin/guides/deploy-multi-process-images.md
  docs/admin/reference/available-images/multi-process-images.md
  images/pulp_ci_centos/Containerfile
  images/s6_assets/init/pulpcore-api
  images/s6_assets/init/pulpcore-content
  images/s6_assets/init/pulpcore-worker
  images/s6_assets/s6-rc.d/pulpcore-api/run
  images/s6_assets/s6-rc.d/pulpcore-content/run
  images/s6_assets/s6-rc.d/pulpcore-worker@1/run
Labels: no-issue, no-changelog
