Repository pulp/pulp-oci-images, pull requests merged in 2025-01, with the labels that each got.

#703 Upgrade pulp-web image to latest nginx image
  CHANGES/644.feature
  CHANGES/702.bugfix
  images/compose/assets/bin/nginx.sh
  images/compose/assets/nginx/nginx.conf.template
  images/compose/compose.yml
  images/pulp-minimal/nightly/Containerfile.webserver
  images/pulp-minimal/stable/Containerfile.webserver
  images/s6_assets/pulp_tests.sh
Labels: multi-commit, no-issue, no-changelog

#709 Restrain podman-compose==1.1.0 for tests to deal with upstream bug
  .github/actions/test_image/action.yml
Labels: backport-3.49, no-issue, no-changelog, backport-3.63

#715 Reduce container layer count by combining RUN commands
  images/pulp-minimal/nightly/Containerfile.webserver
  images/pulp-minimal/stable/Containerfile.webserver
  images/pulp/nightly/Containerfile
  images/pulp/stable/Containerfile
Labels: no-issue, no-changelog
